site_name: Interaktiver Stammbaum
site_url: https://unverbuggt.rüthlein.de/familytree-example
site_author: René Rüthlein

theme:
    name: risonia
    custom_dir: theme_override/
    logo: img/logo.svg
    favicon: img/logo.ico
    extlink: true
    extblank: true
    #manifest: manifest.json
    #serviceworker: service-worker.js

extra_javascript:
  - 'assets/javascripts/d3.v7.min.js'
  - 'assets/javascripts/d3-dag.js'
  - 'assets/javascripts/familytree.js'
  - 'assets/javascripts/familytree_misc.js'

extra_css:
#  - 'css/fonts.css'

nav:
    - Stammbaum: 'index.md'
    - Stammbaum: 'encrypted.md'
    - 'notes.md'

gramps_import:
    filename_in: 'gramps/Untitled_1.json'
    filename_out: 'gramps/data.js'
    base_media: 'C:\gramps'
    thumb_media: 'theme_override/thumbs'
    string_birth: 'Geburt'
    string_death: 'Tod'
    string_birthname: 'Geburtsname'
    string_job: 'Beruf'
    #string_birth: 'Birth'
    #string_death: 'Death'
    #string_birthname: 'Birth Name'
    #string_job: 'Job'
    start: 'I0011'
    openup:
      - 'I0013'
      - 'I0025'
  
plugins:
    - exclude:
        glob:
          - '*.tmp'

    - mkdocs-simple-hooks:
        hooks:
          on_pre_build: "gramps_import:convert_json"
          on_post_build: "download:get_external_assets"

    #- search:
    #    lang: de

    - macros: {}

    - i18n:
        default_language: de
        default_language_only: false
        docs_structure: suffix
        languages:
          default:
            name: Deutsch
            build: true
          en:
            name: English
            build: true
            site_name: "Family tree"
        nav_translations:
          en:
            Stammbaum: Family tree

    - color-theme:
        theme_color: '#446abb'
        secondary_color: 'complementary'
        extra_css_light: 
          - 'extra_css/familytree-light.css'
        extra_css_dark: 
          - 'extra_css/familytree-dark.css'

    - w3css-classes: {}

    - encryptcontent:
        title_prefix: ''
        #global_password: '12345'
        summary: 'Verschlüsselte Seite.'
        placeholder: ''
        password_button_text: 'ENTER'
        decryption_failure_message: 'Falsches Passwort.'
        encryption_info_message: 'Bitte Passwort "12345" eingeben.'
        input_class: 'w3-input'
        button_class: 'w3-button w3-theme-l1 w3-hover-theme'
        hljs: False
        arithmatex: False
        mermaid2: False
        remember_password: true
        #session_storage: false
        encrypted_something:
          myNav: [div, id]
          myToc: [div, id]
          myTocButton: [div, id]
          title-top: [span, id]
          title-head: [span, id]
        search_index: 'dynamically' #dynamically
        password_button: True
        selfhost: true
        selfhost_download: false
        reload_scripts:
          - '#familytree-data'
          - '#familytree-lang'
          - '#theme'
        translations:
          en:
            title_prefix: ''
            summary: 'Encrypted page.'
            placeholder: ''
            password_button_text: 'ENTER'
            decryption_failure_message: 'Wrong password.'
            encryption_info_message: 'Please enter password "12345".'

repo_url: https://github.com/unverbuggt/mkdocs-familytree-example

markdown_extensions:
    - attr_list
    - pymdownx.escapeall:
        hardbreak: true